/*
 * AppConstants
 */

export const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS';
export const LOAD_RESTAURANTS_SUCCESS = 'LOAD_RESTAURANTS_SUCCESS';
export const LOAD_RESTAURANTS_ERROR = 'LOAD_RESTAURANTS_ERROR';
